version: 0.2
phases:
  install:
    runtime_versions:
      java: corretto17
    commands:
      - java --version
      - mvn --version
      - docker info
  pre_build:
    commands:
      - echo "This is pre building"
      - mvn clean compile
  build:
    commands:
      - echo "This is Building Phases"
      - mvn clean package
      - docker build -t mushahid144/mavenapp:v1 .
  post_build:
    commands:
      - echo "This is post building phase......" 
      - docker login  -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - docker push mushahid144/mavenapp:v1
# artifacts:
#   files:
#     - 'target/*.jar'
#     - Dockerfile
#   discard-paths: no
#   name: myjarfiles
    
    
