version: 0.2
phases:
  install:
    runtime_versions:
      java: corretto17
    commands:
      - java --version
      - mvn --version
  pre_build:
    commands:
      - echo "This is pre building"
  build:
    commands:
      - echo "This is Building Phases"
  post_build:
    commands:
      - echo "This is post building phase......" 

