version: 0.2
phases:
  install:
    runtime_versions:
      java: corretto17
    commands:
      - java --version
      - mvn --version
      - docker info
  pre_build:
    commands:
      - echo "This is pre building"
      - mvn clean compile
  build:
    commands:
      - echo "This is Building Phases"
      - mvn clean package
      # - mvn -s settings.xml deploy
      - docker build -t mavenapp:v1 .
  post_build:
    commands:
      - echo "This is post building phase......" 
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 974871161012.dkr.ecr.ap-south-1.amazonaws.com
      - docker tag mavenapp:v1 974871161012.dkr.ecr.ap-south-1.amazonaws.com/codebuild/maven:latest
      # - docker login  -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - docker push 974871161012.dkr.ecr.ap-south-1.amazonaws.com/codebuild/maven:latest
      # - docker push mushahid144/mavenapp:v1
# artifacts:
#   files:
#     - 'target/*.jar'
#     - Dockerfile
#   discard-paths: no
#   name: myjarfiles
    
    
