version: 0.2
phases:
  install:
    commands:
      - echo "Installing .................."
  pre_build:
    commands:
      - echo "This is pre building"
  build:
    commands:
      - echo "This is Building Phases"
  post_build:
    commands:
      - echo "This is post building phase......"
  
